version: '3'

services:
  electroautonomia:
    image: jormeno2020/electroautonomia:0.0.1
    container_name: "electroautonomia"
    restart: always
    networks:
      - traefik-local
    labels:
      - "traefik.http.routers.electroautonomia.rule=Host(`electroautonomia.cl`)"

networks:
  traefik-local:
    external: true
     



